# Generated by Django 4.2.2 on 2023-06-26 12:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=70, verbose_name='Short Name')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is it active?')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='VarietyInDrinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=70, verbose_name='Short Name')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is it active?')),
            ],
            options={
                'verbose_name': 'Variety',
                'verbose_name_plural': 'Varieties',
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=70, verbose_name='Short Name')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is it active?')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price per drink')),
                ('glass_size', models.CharField(choices=[('1', 'S'), ('2', 'M'), ('3', 'L')], max_length=10, verbose_name='Glass size')),
                ('user_trip_ticket', models.FileField(upload_to='api/')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Drink rating from user')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Drink Category')),
                ('category_of_sort_drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.varietyindrinkcategory', verbose_name='Variety In Drink Category')),
            ],
            options={
                'verbose_name': 'Drinks',
                'verbose_name_plural': 'Drinks',
            },
        ),
    ]
