# Generated by Django 4.2.2 on 2023-07-10 08:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=70, verbose_name='Short Name')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is it active?')),
            ],
            options={
                'verbose_name': 'Drink Category',
                'verbose_name_plural': 'Drink Categories',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=70, verbose_name='Short Name')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is it active?')),
            ],
            options={
                'verbose_name': 'Food Category',
                'verbose_name_plural': 'Food Categories',
            },
        ),
        migrations.CreateModel(
            name='VarietyInFoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=70, verbose_name='Short Name')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is it active?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foodcategory', verbose_name='Variety In Food Category')),
            ],
            options={
                'verbose_name': 'Variety In Food Category',
                'verbose_name_plural': 'Varieties In Food Category',
            },
        ),
        migrations.CreateModel(
            name='VarietyInDrinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=70, verbose_name='Short Name')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is it active?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drinkcategory', verbose_name='Variety In Drink Category')),
            ],
            options={
                'verbose_name': 'Variety In Drink Category',
                'verbose_name_plural': 'Varieties In Drink Category',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=70, verbose_name='Short Name')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is it active?')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price per food')),
                ('image', models.FileField(upload_to='api/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foodcategory', verbose_name='Food Category')),
                ('category_of_sort_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.varietyinfoodcategory', verbose_name='Variety In Food Category')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Food products',
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=70, verbose_name='Short Name')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is it active?')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price per drink')),
                ('image', models.FileField(upload_to='api/')),
                ('number_of_drink_glass_sizes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Number of drink glass sizes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drinkcategory', verbose_name='Drink Category')),
                ('category_of_sort_drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.varietyindrinkcategory', verbose_name='Variety In Drink Category')),
            ],
            options={
                'verbose_name': 'Drinks',
                'verbose_name_plural': 'Drinks',
            },
        ),
    ]
