# Generated by Django 4.2.2 on 2023-06-27 09:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=70, verbose_name='Short Name')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is it active?')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='VarietyInDrinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=70, verbose_name='Short Name')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is it active?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Drink Category')),
            ],
            options={
                'verbose_name': 'Variety',
                'verbose_name_plural': 'Varieties',
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=70, verbose_name='Short Name')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is it active?')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price per drink')),
                ('image', models.FileField(upload_to='api/')),
                ('number_of_drink_glass_sizes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Number of drink glass sizes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Drink Category')),
                ('category_of_sort_drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.varietyindrinkcategory', verbose_name='Variety In Drink Category')),
            ],
            options={
                'verbose_name': 'Drinks',
                'verbose_name_plural': 'Drinks',
            },
        ),
    ]
