# Generated by Django 4.2.2 on 2023-06-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='user_trip_ticket',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='glass_size',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='rating',
        ),
    ]
