# Generated by Django 4.2.2 on 2023-07-13 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_drinks_need_milk_drinks_need_syrup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='category_of_sort_drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.varietyindrinkcategory', verbose_name='Variety In Drink Category'),
        ),
    ]
