# Generated by Django 4.2.2 on 2023-07-13 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_food_category_of_sort_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price per drink'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price per food'),
        ),
    ]
