# Generated by Django 4.2.2 on 2023-07-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_drinks_image_alter_drinks_need_milk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='image',
            field=models.FileField(default='api/coffee.webp', upload_to='api/'),
        ),
    ]
