# Generated by Django 4.2.2 on 2023-07-13 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_drinks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.FileField(default='api/food.jpg', upload_to='api/'),
        ),
        migrations.AlterField(
            model_name='varietyindrinkcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drinkcategory', verbose_name='Drink Category'),
        ),
        migrations.AlterField(
            model_name='varietyinfoodcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foodcategory', verbose_name='Food Category'),
        ),
    ]
