# Generated by Django 4.2.2 on 2023-07-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_food_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='need_milk',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='need_syrup',
        ),
    ]
