# Generated by Django 4.2.2 on 2023-07-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_drinks_need_milk_remove_drinks_need_syrup'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkcategory',
            name='image',
            field=models.FileField(default='api/coffee.webp', upload_to='api/'),
        ),
    ]
