# Generated by Django 4.2.2 on 2023-07-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_drinkcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='image',
            field=models.FileField(default='api/food.jpg', upload_to='api/'),
        ),
    ]
